[package]
name = "mymodifer"
edition = "2024"
version.workspace = true

[dependencies]
# TODO

[workspace]
resovler = "2"
members = []
exclude = []

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
# TODO
